on:
  pull_request:
    types: [opened]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Sending Slack Message
        uses: slackapi/slack-github-action@v1.21.0
        with:
          channel-id: ${{ secrets.SLACK_TARGET_CHANNEL_ID }}
          slack-message: echo 'PR for "${{ github.event.pull_request.title }}" (${{ github.head_ref || github.ref_name }}) \n${{ github.event.pull_request.html_url }}'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}