on:
  pull_request:
    types: [opened]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    env:
      PR_TITLE: ${{ github.event.pull_request.title }}
      PR_URL: ${{ github.event.pull_request.html_url }}
      PR_OPENER: ${{ github.event.pull_request.user.login }}
      PR_REVIEWER: ${{ toJSON(github.event.pull_request.requested_reviewers) }}
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    steps:
      - name: Sending Slack Message
        uses: slackapi/slack-github-action@v1.21.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: ${{ secrets.SLACK_TARGET_CHANNEL_ID }}
          slack-message: "PR for \"${{ env.PR_TITLE}}\" (${{ env.BRANCH_NAME }})\n${{ env.PR_URL }}\n\Opened by: ${{ env.PR_AUTHOR }}\nRequested Reviewer: ${{ env.PR_REVIEWER }}"
