on:
  pull_request:
    types: [opened, closed]

jobs:
  PR-Created:
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: Run Construct PR Slack Message
        id: pr-slack-message
        uses: ./.github/actions/construct-pr-slack-message.yml

      - name: Sending Slack Message
        uses: slackapi/slack-github-action@v1.26.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: ${{ secrets.SLACK_TARGET_CHANNEL_ID }}
          payload: |
            {
              "text": "${{ steps.pr-slack-message.outputs.output }}"
            }

  PR-Closed:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      PR_TITLE: ${{ github.event.pull_request.title }}
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      PR_MERGER: ${{ github.event.pull_request.merged_by.login }}
    steps:
      - name: Find previous Slack message
        run: |
          #!/bin/bash

          # Call the Slack API to search for messages
          response=$(curl -s -X GET "https://slack.com/api/search.messages" \
            -H "Authorization: Bearer ${{ secrets.SLACK_USER_TOKEN }}" \
            -G --data-urlencode "query=PR for \"${{ env.PR_TITLE}}\" (${{ env.BRANCH_NAME }})" \
            -G --data-urlencode "channel=${{ secrets.SLACK_TARGET_CHANNEL_ID }}")

          thread_ts=$(echo $response | jq -r '.messages.matches[0].ts')
          
          echo "::set-output name=thread_ts::$thread_ts"
        id: find-thread-ts

      - name: Run Construct PR Slack Message
        id: pr-slack-message
        uses: ./.github/actions/construct-pr-slack-message.yml

      - name: Update previous Slack Message
        uses: slackapi/slack-github-action@v1.26.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: ${{ secrets.SLACK_TARGET_CHANNEL_ID }}
          update-ts: ${{ steps.find-thread-ts.outputs.thread_ts }}
          payload: |
            {
              "text": "✅ ${{ steps.pr-slack-message.outputs.output }}"
            }

      - name: Sending Slack Reply
        uses: slackapi/slack-github-action@v1.26.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: ${{ secrets.SLACK_TARGET_CHANNEL_ID }}
          payload: |
            {
              "thread_ts": "${{ steps.find-thread-ts.outputs.thread_ts }}",
              "text": "Merged by ${{ env.PR_MERGER }}"
            }
