on:
  pull_request:
    types: [opened, closed]

jobs:
  PR-Created:
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    runs-on: ubuntu-latest
    env:
      PR_TITLE: ${{ github.event.pull_request.title }}
      PR_URL: ${{ github.event.pull_request.html_url }}
      PR_OPENER: ${{ github.event.pull_request.user.login }}
      PR_REVIEWERS: ${{ toJSON(github.event.pull_request.requested_reviewers.*.login) }}
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    steps:
      - name: Sending Slack Message
        uses: slackapi/slack-github-action@v1.21.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: ${{ secrets.SLACK_TARGET_CHANNEL_ID }}
          slack-message: "PR for \"${{ env.PR_TITLE}}\" (${{ env.BRANCH_NAME }})\n${{ env.PR_URL }}\n\nOpened by: ${{ env.PR_OPENER }}\nRequested Reviewers: ${{ env.PR_REVIEWERS }}"

  PR-Closed:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      PR_MERGER: ${{ github.event.pull_request.merged_by }}
    steps:
      - name: Sending Slack Message
        uses: slackapi/slack-github-action@v1.21.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: ${{ secrets.SLACK_TARGET_CHANNEL_ID }}
          slack-message: "Merged by ${{ env.PR_MERGER }}"
